apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-{{ .Release.Name }}
  labels:
    {{ include "nlp-pipeline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - name: tcp-port
      port: {{ .Values.fastapi.service.port }}
      targetPort: 8000
      protocol: TCP
